# Generated by Django 4.2.3 on 2024-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups thisMatriculas user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuarios_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
