# Generated by Django 4.2.3 on 2024-05-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='matricula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.matricula'),
        ),
    ]
