# Generated by Django 4.2.3 on 2024-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='matricula',
            field=models.IntegerField(max_length=9, unique=True),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
