# Generated by Django 4.2.3 on 2024-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_matricula_delete_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
