# Generated by Django 5.0.6 on 2024-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
