# Generated by Django 5.0.6 on 2024-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuarios_bairro_usuarios_cep_usuarios_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
