# Generated by Django 5.0.6 on 2024-06-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_like_sexualidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='sexualidade',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexualidade',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'feminino'), ('A', 'ambos'), ('N', 'nada')], default='N', max_length=1),
        ),
    ]
